### ISSUE TITLE
Delete last ANDIF and entire event trigger disappears

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#242] opened 2021-12-18 20:10 UTC
HS 4.2.6.0

Setup an event trigger with an IF and at least one ANDIF
Edit event trigger to delete via trashcan icon all ANDIF conditions
Upon deletion of the last ANDIF the entire trigger (IF and other remaining conditions) is removed and cannot be restored

**Comment by spudwebb** [comment] 2022-01-12 16:06
I can't reproduce this issue with HS 4.2.7.0, can you?

**Comment by mcsSolutions** [comment] 2022-01-14 18:17
I was also not able to recreate it

**Comment by spudwebb** [comment] 2022-01-14 19:36
I'm closing this issue, feel free to reopen if you can recreate it.

**Closed by spudwebb** 2022-01-14 19:36 UTC
Labels: Feedback, Incident Report
