### ISSUE TITLE
Legacy PluginExtraData overwritten with "thermnumber1"!

### ISSUE THREAD

**Issue by wvuyk** [HomeSeer/Plugin-SDK#106] opened 2020-07-18 10:36 UTC
Hello,

My plugin is supporting thermostats. When I install HS4 over HS3 and use the HS3 version of the plugin, the PluginExtraData is removed! Instead, it is replaced with a item named "thermnumber1", that is not coming from the plugin causing deserialization to go wrong....

This is not noticed when HS4 and the legacy plugin are started the first time. But the second time the plugin has lost all information in the PluginExtraData object and thus cannot control the device correctly anymore. Why is HS4 adding this to legacy plugin devices?
Please correct this ASAP?

@rjhdakota , @jldubz

**Comment by wvuyk** [comment] 2020-09-02 21:57
@rjhdakota This is a real issue. Why is this not looked at?

**Comment by rjhdakota** [comment] 2020-09-02 22:01
HS3 was doing that also, it needs to save the number of the thermostat for matching later. This is not new. Is it overwriting other information that is there?

**Comment by wvuyk** [comment] 2020-09-02 22:05
It is overwriting the Plugin data of HS3 plugins, removing all that is needed for th plugin?

**Comment by wvuyk** [comment] 2020-09-02 22:06
HS3 PED data is emptied it should say

**Comment by rjhdakota** [comment] 2020-09-02 22:10
I will look at the code and see what it is doing. I know HS3 needs to save the info for use later and my guess is that all the Thermostat plugins released so far have not been using the PED. This is going to be a big job to fix as any existing system will be looking in the PED for this info so if I remove it in an update of HS4 it will break all existing systems. So some kind of workaround will need to be developed. Will let you know what I come up with.

**Comment by wvuyk** [comment] 2020-09-02 22:13
I was using the PED already in the HS3 version of the plugin, also for Thermostats. Probably it never caused issues because it was is the same serialization? But with HS4, serialization has changed. I guess this is causing issues?

**Comment by SteveMSJ** [comment] 2020-09-03 14:21
I also have this problem with my HS3 SDJ-VStats plug-in.
I store all the configuration information in the PED of the root device of each VStat.  This has worked perfectly for years in HS3, and in early beta versions of HS4, but at some point with the release versions of HS4 the PED is being cleared, completely breaking the plug-in.  It doesn't happen on all systems, which is weird and I wasn't able to pin down a common setup that caused the issue.
I submitted a bug report many weeks ago HSCS-325 but it is Waiting for Support.
What I found was that removing Collections and Arrays from my stored PED circumvented the issue, so I updated the plug-in to convert the data and that sorted it for my users.
NOW with HS4 4.1.5.0 the problem has resurfaced despite the plug-in only using basic data types in the PED.  Again it isn't showing on all systems but those that it is are crippled.

It appears to only relate to thermostat devices.  I haven't seen the issue with other plug-ins.

Also of interest a similar problem has been reported on the message board for the Omnistat 3 plug-in.  In that case the author appears to have linked it with HSTouch but it is the same problem with HS4 deleting the PED of the thermostat.  His bug report is apparently HSCS-577.

This is a major issue.

Steve

**Comment by rjhdakota** [comment] 2020-09-03 18:54
HS needs to associate a number with each thermostat for HSTouch, so a number is assigned to each thermostat and saved in the PED under a named entry named "thermnumber1". 

I do see a problem though, when it finds a new thermostat it gets the PED then it clears it. I have no idea why it's doing that, I suspect test code. I will remove it and post a build for you to try.

**Comment by rjhdakota** [comment] 2020-09-03 19:11
Can you try this build and see if the issue is resolved:
https://homeseer.com/updates4/SetupHS4_4_1_5_1.msi

**Comment by SteveMSJ** [comment] 2020-09-04 11:44
Thanks for addressing this, it has been a real headache for me.

At least one of my users has now tested 4.1.5.1 and thinks it has cured the problem.  I can't test because I can't replicate the error on my current system.  That is why tracking down the issue has been such a problem.

I will report back as I hear from more users.

Steve

**Comment by rjhdakota** [comment] 2020-09-04 13:13
I think the PED should probably be used only by the owning plugin, although I am not sure we state than anywhere. But I might look at moving that info out of the PED so I don't conflict with plugin data.

**Comment by SteveMSJ** [comment] 2020-09-04 13:31
That was always my understanding and I'm pretty sure it is stated somewhere.  There has been the odd argument between plug-in authors over the years about writing to other owners PED.  I remember one got particularly heated with threats issued before the offending author backed down and apologised. 

Not related but, I historically only use UnNamed entries because way back there was an issue with Named entries when running a plug-in remotely addressing HS3 on linux.  I don't remember the exact details and I think it was a mono version 3 problem that I'm sure is no longer an issue, but I got into the habit.  When I write to PED I clear all UnNamed entries but I don't clear Named entries so I'm not deleting the HSTouch added thermostat number.  It would still be better to move it out of PED and keep that exclusively for the owning plug-in.

There is a thread appeared today about yet another thermostat plug-in (Radio Thermostat) not working after upgrading to HS4.  Probably the same issue of deleted PED so the sooner this fix is officially released the better.

Steve

**Comment by rjhdakota** [comment] 2020-09-04 14:37
I do agree with this. I will see if I can move that out of the PED for the next update.

**Comment by SteveMSJ** [comment] 2020-09-04 16:03
Sounds good.
Thanks.

**Comment by wvuyk** [comment] 2020-09-04 17:44
I remember a situation where my plugin was throwing errors because another plugin author added plugin objects in the PED. If a user deinstalled his plugin, the plugin would not remove its object from the devices checked by his plugin. From then on the errors were thrown as this plugin was not to be found anymore.
But that was an addition to the PED with non 'standard' objects. 

I think the thermnumber item is a standard object, like string or integer. If adding this item to a PED can be done without clearing all other items, I am fine with it from here. So if moving it out of PED is not really easy, prevent the clear of PED would be fine for my plugin.

**Comment by rjhdakota** [comment] 2020-09-04 17:48
The 4.1.5.1 build that I posted removes the clearing of the PED. So we have that settled. I will remove it from the PED if I can find an easy way to do it without breaking existing users. That is always the issue. I will need to read all the current thermostat PEDS, save it in an INI file, then mark that system as upgraded. Its a bit messy. If they every go back to a pre 4.1.5.1 version, they will be broken. But I cannot guard against that.

**Comment by SteveMSJ** [comment] 2020-09-09 10:58
All my users that have tested 4.1.5.1 report that it appears to have cured the problem:)

**Comment by spudwebb** [comment] 2020-12-07 15:22
I'm closing this issue as I believe it is now fixed.

**Closed by spudwebb** 2020-12-07 15:22 UTC
Labels: Feedback, Incident Report
