### ISSUE TITLE
SDK InputView does not allow EInputType.Time

### ISSUE THREAD

**Issue by mitchmitchell** [HomeSeer/Plugin-SDK#250] opened 2022-01-10 02:17 UTC
**Environment and System Config**
- OS: Linux
- Language: VB
- IDE: VS2022
- HomeSeer Version: 4.2.7.0
- PluginSDK Version: 1.3.1.0

**Describe what you would like to see added or changed**
In the function IsValueValidForType the InputView accepts a type pf EInputType.Time

`
			switch (InputType) {
				case EInputType.Text:
				//TODO validate date and time input
				case EInputType.Date:
				case EInputType.Time:
				case EInputType.DateTime:
					//Anything is valid for text
					return true;
				case EInputType.Number:
				case EInputType.Decimal:
					return float.TryParse(value, out _);
				case EInputType.Email:
					try {
						var address = new System.Net.Mail.MailAddress(value);
						return address.Address == value;
					}
					catch (Exception) {
						return false;
					}
				case EInputType.Url:
					return Uri.TryCreate(value, UriKind.Absolute, out _);
				case EInputType.Password:
					//Password types merely restrict the visibility of characters not the input
					return true;
				default:
					return false;
			}
`

However further down in the code it rejects this input type:

` sb.Append(GetIndentStringFromNumber(indent+1));
            string typeString = null;
            switch (InputType) {
	            case EInputType.Text:
		            typeString = "text\" ";
		            break;
	            case EInputType.Number:
		            typeString = "number\" step=\"1\" pattern=\"[0-9]*\" ";
		            break;
	            case EInputType.Email:
		            typeString = "email\" ";
		            break;
	            case EInputType.Url:
		            typeString = "url\" ";
		            break;
	            case EInputType.Password:
		            typeString = "password\" ";
		            break;
	            case EInputType.Decimal:
		            typeString = "number\" step=\"0.001\" ";
		            break;
	            default:
		            throw new ArgumentOutOfRangeException();
            }`

This inconsistency makes it difficult to support thermostat scheduling which require a time input.

**Priority**
How important is this to you on a scale of 1-5?
3. Medium

**Comment by mitchmitchell** [comment] 2022-01-10 02:19
That insert code editor sure messes up the code formatting.


 sb.Append(GetIndentStringFromNumber(indent+1));
            string typeString = null;
            switch (InputType) {
	            case EInputType.Text:
		            typeString = "text\" ";
		            break;
	            case EInputType.Number:
		            typeString = "number\" step=\"1\" pattern=\"[0-9]*\" ";
		            break;
	            case EInputType.Email:
		            typeString = "email\" ";
		            break;
	            case EInputType.Url:
		            typeString = "url\" ";
		            break;
	            case EInputType.Password:
		            typeString = "password\" ";
		            break;
	            case EInputType.Decimal:
		            typeString = "number\" step=\"0.001\" ";
		            break;
	            default:
		            throw new ArgumentOutOfRangeException();
            }

**Comment by jldubz** [comment] 2022-01-10 03:40
This is a duplicate of https://github.com/HomeSeer/Plugin-SDK/issues/104

**Closed by jldubz** 2022-01-10 03:40 UTC
Labels: duplicate
