### ISSUE TITLE
Building buttons along with dropdown adds the button values to the dropdown

### ISSUE THREAD

**Issue by rmasonjr** [HomeSeer/Plugin-SDK#294] opened 2022-06-28 20:53 UTC
#### OS
[Windows,]
#### HS Version
[v4.2.13.0]
#### PSDK Version
[v1.4.1.0]
#### Language
[VB]
#### IDE
[VS2017]
#### Dev OS
[Windows]
### Plugin
What plugin is this issue for?
OMNI
## Problem
There are 2 screenshots attached.  Screenshot1 shows where I add an Off/On/Toggle button along with a dropdown to Dim/Brighten a device.  The Off/On is added to the dropdown although I'm creating the SortedDictionary separately.

I need them separated since their EControlUse are all different.

Also, why doesn't the Toggle button show in the GUI?  I have it on the correct row/col but it's not displaying.

Thanks
Rob

## Screenshots
[screenshot2](https://user-images.githubusercontent.com/11462627/176285508-4a6f4b29-fb3f-4e24-9cdf-25eaaa1c3376.png)
[screenshot1](https://user-images.githubusercontent.com/11462627/176285509-483884f9-bffd-413a-a1d1-b85a7c005bac.png)

**Comment by rmasonjr** [comment] 2022-07-06 14:13
More Info:

When you use Alexa/GH for voice control, I am under the impression that the EControlUse drives the process.
For example, "Alexa, Dim the lamp to 10%" would use the device's EControlUse.Dim property to dim the device.
Also, "Alexa, turn off the lamp" would use the device's EControlUse.Off property to turn off the device.

Now, I have a device where I want 2 buttons, On and Off, with their EControlUse set to On/Off.
I also want a dropdown with EControlUse.Dim, however, a dropdown control is adding On and Off to the select list.
Since the dropdown can only have one EControlUse, I dont think my device will be controllable by Alexa/GH.

**Comment by Sgt-Shultz** [comment] 2022-07-06 15:20
You should only need one set of values in the drop list, the 10% to 90%..., the verbs 'dim' and 'brighten' are handled by the voice command control (Alexa/GH) as either an absolute value (set to 20%), or a delta (brighten by 20%).
The eControlUse enums should only be set one time per device..., this includes all the features of a device since they are all part of the overall object. So in your example you should have a root device that has no controls on it, then a feature with an On button, an Off button, and a drop list with a range from 10% to 90%. Each one of those objects would have a unique control use associated with it, so that the discovery and command processes can determine what traits the devices has and what value to set the device to. This means the drop list would have one control use of 'dim'. At a level of 0, the device is off so instead of the drop list, the off button would be used. Same for a level of 100.

For the toggle button, I'm thinking perhaps the value it is set to is also a value in another control..., maybe the drop list?

A screenshot of your enums would be helpful so I can see the values you using in the code.

**Comment by Sgt-Shultz** [comment] 2022-07-06 17:47
I'm not seeing anything that looks off.
Have you tried putting the droplist on a second feature? It's all the same device, but that might make a change in it's behavior.

**Comment by rmasonjr** [comment] 2022-07-06 18:12
It's definitely a problem with the AddTextDropDown code.

I commented out the last line and replaced it with an AddSlider and it looks fine.  See attached screenshot4

 Dim ff = FeatureFactory.CreateFeature(OMNI_NAME).
            WithName(u.unitName).
            WithLocation(OMNI_NAME & " Units").
            WithLocation2(OMNI_NAME).
            WithMiscFlags(withFlags).
            WithoutMiscFlags(withoutFlags).
            WithExtraData(PED).
            AsType(EFeatureType.Generic, 0).WithDefaultValue(0).
            AddButton(0, "Off", New ControlLocation(1, 1), EControlUse.Off).
            AddButton(255.0, "On", New ControlLocation(1, 2), EControlUse.On).
            AddButton(101.0, "Toggle", New ControlLocation(1, 3), EControlUse.OnAlternate).
            AddSlider(New ValueRange(10.0, 90.0), New ControlLocation(2, 1, 3), EControlUse.Dim)
        ''AddTextDropDown(GetUPBDropDownValues, New ControlLocation(2, 1, 3), EControlUse.Dim)

      

![screenshot4](https://user-images.githubusercontent.com/11462627/177615685-dced5bbd-611c-49ec-8f26-679aa28a11b6.png)

**Comment by Sgt-Shultz** [comment] 2022-07-06 19:48
It's an issue somewhere in the page build for the drop list.
Putting the drop list on a second feature of the device corrects the issue for both the drop list and the buttons.
I'll put a ticket in for this so it can be looked at.

**Comment by spudwebb** [comment] 2022-08-22 15:07
It's tracked as HS-1058
And it's a duplicate of #89, so I'm closing this issue

**Closed** 2022-08-22 15:07 UTC
Labels: To Do
