### ISSUE TITLE
OnNewTrigger() is not called when sub-trigger is changed

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#150] opened 2021-01-24 14:41 UTC
If I have sub-trigger types, I select one, then fill out the info, so IsFullyConfigured() returns 'true' - then I select another sub-trigger, but OnNewTrigger() isn't called anymore.

The only function is called - IsFullyConfigured(), but even if I re-create ConfigPage in IsFullyConfigured - the page html doesn't change anymore.  So it still shows UI for first sub-trigger type.

**Comment by alexbk66** [comment] 2021-01-24 14:46
![image](https://user-images.githubusercontent.com/2533315/105633854-2a7c2980-5eaf-11eb-9091-27730b2212b4.png)

**Comment by mnsandler** [comment] 2021-01-24 15:26
Alex
i think i ran into the same problem. the lifecycle doesn't account for 'changing' trigger types. to work around this I did the following

```
		Public Sub New(ByVal id As Integer, ByVal eventRef As Integer, ByVal selectedSubTriggerIndex As Integer, ByVal dataIn As Byte(), ByVal inListener As TriggerTypeCollection.ITriggerTypeListener, Optional ByVal debugLog As Boolean = False)
			MyBase.New(id, eventRef, selectedSubTriggerIndex, dataIn, inListener, debugLog)

			MyEditTrigger()
		End Sub
```

MyEditTrigger() handles 'editing' by clearing the views and starting clean. below is one example. if the view doesn't match the new subtrigger selection i reconfigure the configpage. otherwise the routine basically does nothing.


```
				Select Case SelectedSubTriggerIndex
					Case INSTEON_TRIGGER_TYPES.HEARTBEAT

						If Not ConfigPage.ContainsViewWithId(HeartbeatDeviceFieldName) Then
							ConfigPage.RemoveAllViews()
							DeviceList = BuildDeviceList(FilterOptions.HasHeartbeat) ' ***
							ConfigPage.AddView(New SelectListView(HeartbeatDeviceFieldName, "Select a Heartbeat Device", DeviceList.Values.ToList, DeviceList.Keys.ToList))
						End If
```

hope this helps

**Comment by alexbk66** [comment] 2021-01-24 15:41
Something sucks here

**Comment by mnsandler** [comment] 2021-01-24 16:00
I hear you. this is the ticket I posted on the same topic
https://github.com/HomeSeer/Plugin-SDK/issues/133

**Comment by alexbk66** [comment] 2021-01-24 16:09
29 days ago

**Comment by alexbk66** [comment] 2021-01-25 01:03
Mark, I found more reliable workaround - when creating the trigger Page I add a label storing current SelectedSubTriggerIndex.
![image](https://user-images.githubusercontent.com/2533315/105649521-b2405300-5f04-11eb-8b6b-c251d092c761.png)
Then in the trigger ctors i compare the stored value with SelectedSubTriggerIndex:
![image](https://user-images.githubusercontent.com/2533315/105649599-f2073a80-5f04-11eb-8d3c-ec70322ee611.png)
Would be nice to be able to store some **hidden data** in the view, otherwise the label is visible (I can probably hide it via html, but CBB) 
![image](https://user-images.githubusercontent.com/2533315/105649640-20851580-5f05-11eb-841f-763f7f00cfe0.png)

**Comment by mnsandler** [comment] 2021-01-25 12:59
do you think its worth submitting a request to have a HiddenView added to 
public abstract class AbstractView

**Comment by alexbk66** [comment] 2021-01-25 14:09
> do you think its worth submitting a request to have a HiddenView added to
> public abstract class AbstractView

Yeah, would be nice.  For now I use `$"<div style='display: none;'>{ind_lbl}</div>"` to make it hidden

**Comment by spudwebb** [comment] 2021-01-25 20:52
I'm closing this issue as it is a duplicate of #133

**Closed by spudwebb** 2021-01-25 20:52 UTC
Labels: duplicate
