### ISSUE TITLE
Feature config page is linked to root device config?

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#157] opened 2021-01-29 10:39 UTC
It's a nice feature - when you click on any child feature device - it has config tab from the parent root device.
But.

In my AKGoogleCalendar plugin root device is a calendar (with its config) and each child device represents an event in the calendar.
![image](https://user-images.githubusercontent.com/2533315/106265176-c1176480-627a-11eb-9e0f-6478ae6e3d63.png)

When I click on each child device - I can see the particular calendar event info:
![image](https://user-images.githubusercontent.com/2533315/106263417-74cb2500-6278-11eb-907c-d1e54a291105.png)

In HS4 it's currently not possible?  So what are other options?

I think if child (feature) device `HasJuiDeviceConfigPage` returns `true` - then it should be possible to define `GetJuiDeviceConfigPage` for child device.

Another option - parent (root) `GetJuiDeviceConfigPage` could take the selected feature RefId argument.

**Comment by spudwebb** [comment] 2021-02-03 19:20
duplicate of #86

**Comment by alexbk66** [comment] 2021-02-04 05:26
Closing as Duplicate

**Comment by alexbk66** [comment] 2021-02-16 06:18
I actually need GetJuiDeviceConfigPage for each feature for porting AKSmartDevice plugin. 

Adding a droplist as suggested here https://github.com/HomeSeer/Plugin-SDK/issues/86#issuecomment-609878284 is not really user friendly and in some cases not feasible solution.  AKEnphaseEnvoy plugin can have 50 and more children devices.

It's quite a misleading implementation you created - I expect my child device to handle the page - but suddenly you call the function from the parent?

Is it possible **at least** to pass the feature RefId to GetJuiDeviceConfigPage?

**Comment by alexbk66** [comment] 2021-02-16 07:03
The page URL is `http://192.168.1.83/devices.html?ref=1765&subpage=devprop&feature=1767`

It has both parent and child RefId - how can I get the child id???

**Comment by spudwebb** [comment] 2021-05-11 17:13
closing as it is a duplicate see my answer in #86

**Closed by spudwebb** 2021-05-11 17:13 UTC
Labels: duplicate
