### ISSUE TITLE
GroupViews do not work on Action/Trigger config pages

### ISSUE THREAD

**Issue by jldubz** [HomeSeer/Plugin-SDK#32] opened 2019-10-30 19:00 UTC
Per @wvuyk on https://github.com/HomeSeer/Plugin-SDK/issues/28

> I got some of the event action working. It appears - with a lot of try and see....- that you cannot use GroupViews here.

Further investigation is needed and documentation should be updated to reflect this.

**Comment by dcorsus** [comment] 2020-03-01 23:58
Is this closed? I coded this up this morning and it isn't working for me either. I send email to @rjhdakota . It seems to error in jui-events.js in procedure viewValueChanged when trying to pick up the pageid.

**Comment by dcorsus** [comment] 2020-03-02 00:00
`
From: dirk@famcorsus.com <dirk@famcorsus.com> 
Sent: Sunday, March 1, 2020 11:12 AM
To: 'Richard J Helmke' <rjh@homeseer.com>
Subject: RE: Maybe an easy question for you

Here is how I created the GroupView

                    If LinkListIndex = -1 Then
                        Dim linkPlayerView As New ViewGroup(OptionLinkPlayerSlId, OptionLinkPlayerSlName)
                        Dim linkPlayerList As New Dictionary(Of String, String)
                        For Each HSDevice As MyUPnpDeviceInfo In myHSDeviceLinkedList
                            If HSDevice.ZonePlayerControllerRef IsNot Nothing Then
                                ' special case, just find the first player with a reference
                                Dim playername As String = HSDevice.ZonePlayerControllerRef.ZoneName
                                Dim playerUDN As String = HSDevice.ZonePlayerControllerRef.UDN
                                If HSDevice.ZonePlayerControllerRef.ZoneModel.ToUpper <> "SUB" Then
                                    linkPlayerList.Add(playerUDN, playername)
                                End If
                            End If
                        Next
                        Dim playerToggles = linkPlayerList.[Select](Function(kvp) New ToggleView(kvp.Key, kvp.Value, True) With {
                              .ToggleType = HomeSeer.Jui.Types.EToggleType.Checkbox,
                              .IsEnabled = False
                                  }).ToList()
                        cpf.WithGroup(OptionLinkPlayerSlId, OptionLinkPlayerSlName, playerToggles)
                    End If


From: dirk@famcorsus.com <dirk@famcorsus.com> 
Sent: Sunday, March 1, 2020 11:08 AM
To: 'Richard J Helmke' <rjh@homeseer.com>
Subject: RE: Maybe an easy question for you

Hi Rich, so far I haven’t made any progress with this so I’ve set it aside, don’t think it is important right now.

Here’s what I tried:

When I read the control from old HS3 info, all location info appears correct, I can verify that by going to the HS devices page, click on the device, select “Status/Graphics”. There I see just one feature, when I click on it, all looks proper and I see no difference whether it was generated by my HS4 PI from scratch (and all is OK ie only one “Control” button) or migrated from HS3 to HS4 where I have 3 “Control” buttons and all 3 open a window with exact same controls.
I tried to change the location info during migration, I tried regenerating the location info from scratch during migration but nothing seems to make a difference. You do need to remember that the feature this control is on, has been “changed” from the root device in HS3 to a feature now attached to a (new) root, so I suspect the issue is somewhere on something else that gets carried over from HS3. 

I did notice that you can’t change/clear misc flags or so far I haven’t found that.

Now that what is really important right now (might be a Jon question but I start with you).

As part of my actions, I have an action (linking speakers) that require a multi selection object. So the only way I could figure out to do this is to use a ViewGroup with checkboxes on them. I hope this is the right way to do it.

Here’s a screenshot how it looks:
 

If I now select a player and save the action, nothing gets saved. I see an error in jui-events.js. The following code errors when I select a player, and it errors retrieving the pageid.
    function viewValueChanged(event) {
        var view = event.target;
        var pagediv = document.getElementById(view.id + ".par").parentNode;
        var pageid = pagediv.attributes.getNamedItem("pageid").value;
        var viewchange;
        var viewid;
        var viewtype;
        var viewvalue;

I’m not 100% clear but from the HTML generated, I think when you add a view as opposed to a selection, I think the pagid info sits on a higher level. Here is the HTML code

I hope you can read it in the picture below when you hunt for the element with “.par” in it you get the node below: 
<div id="3-3017-RINCON_000E58C174DE01400.par" class="jui-view jui-toggle">

Its parent is:
<div id="3-3017-LinkPlayerAction" class="jui-view jui-group">

And not 
<div class="container jui-page" pageid="3-3017">

Causing no pageid to be retrieved and all fails. Am I adding this viewgroup wrong or is there a flaw in the .js code?

 








`

**Comment by dcorsus** [comment] 2020-03-02 00:04
@dcorsus

**Comment by dcorsus** [comment] 2020-03-20 13:27
@rjhdakota @jldubz 
Any progress gents? Important to me. Thanks for providing an update.

**Comment by rjhdakota** [comment] 2020-04-20 18:58
Logged as issue PSDK-57

**Comment by sjhill01** [comment] 2020-05-03 16:30
The bigger issue here, IMHO, is the lack of a proper multi-select type view...

**Comment by dcorsus** [comment] 2020-05-10 02:10
Rich suggested I post an update here.
I made a quick solution to jui-event.js as follows:

`    function viewValueChanged(event) {
        var view = event.target;
        var pagediv = null;
        if (view.hasAttribute("par-id")) {
            pagediv = document.getElementById(view.getAttribute("par-id")).parentNode;
        }
        else {
            pagediv = document.getElementById(view.id + ".par").parentNode;
        }
        // CHANGED HERE BY DCOR
        //var pageid = pagediv.attributes.getNamedItem("pageid").value; old code
        // start new code
        var pageid = null;
        if (pagediv != null) {
            if (pagediv.hasAttribute("pageid")) {
                pageid = pagediv.attributes.getNamedItem("pageid").value;
            }
            else {
                // the page-id set higher up , in my case actuaally the grandparent instead of parent
                for (i=0;i<2;i++) {
                    var justNextParent = pagediv.parentNode;
                    if (justNextParent != null) {
                        if (justNextParent.hasAttribute("pageid")) {
                            pageid = justNextParent.attributes.getNamedItem("pageid").value;
                            pagediv = justNextParent;
                            break;
                        }
                        else {
                            pagediv =justNextParent;
                        }
                    }
                    else {
                        break;
                    }
                }
            }
        }

`

**Comment by dcorsus** [comment] 2020-05-13 18:35
@jldubz just checking whether you got notified of my posting above and/or whether you have any questions or some idea when this may make it into an official release? I have it working in my setup but any upgrade will make me lose it if not included.

**Comment by dcorsus** [comment] 2021-02-22 02:21
@jldubz @rjhdakota 
Any updates to this issue? I just tried it in the new version 4.1.13.0 and it still doesn't work. 
Very easy to troubleshoot, I use Chrome, open debug tool and when I select any of the options it errors like this

events.html?ref=10&subpage=event.html:1212 Uncaught TypeError: Cannot read property 'value' of null
    at HTMLInputElement.viewValueChanged (events.html?ref=10&subpage=event.html:1212)
    at HTMLDocument.dispatch (jquery-3.4.0.min.js:2)
    at HTMLDocument.v.handle (jquery-3.4.0.min.js:2)

**Comment by dcorsus** [comment] 2021-03-02 19:04
@jldubz 
Is this solved in sdk v1.2.3.0? The description of the pull request sounds very different from the issue reported.
Can you confirm?

**Comment by jldubz** [comment] 2021-03-02 21:00
@dcorsus,

No. Sorry for the confusion. It looks like GitHub is grabbing our bitbucket pull request numbers and matching them up incorrectly.

This is still on the table for v1.3. I am pulling this work open as soon as I work through some issues with the Z-Wave plugins, HomeSeer Mobile, and Z-Flash.

**Comment by dcorsus** [comment] 2021-03-18 02:29
@jldubz 

Checking in again. Understand you have other priorities but may I suggest you included the code I provided on May 9th now close to a year ago, how you can "work around" the issue without causing ANY problem to your existing code? See a few posting above this posting.

The code ONLY gets triggered when you actually error because the parent node cannot be retrieved because you are 2 levels away from the right parent.

It is really easy to verify, if you create some code and drop in a groupview, use chrome and open the developer tool. As soon as you click on a item, it tells you exaclty where it goes wrong. See picture here

![image](https://user-images.githubusercontent.com/12876008/111564490-08888000-8757-11eb-95dc-d2d6eaa46d62.png)

**Comment by spudwebb** [comment] 2021-03-30 22:00
This is fixed in HS version 4.1.15.0. Please test and reopen this issue if you still have problems.

**Closed by spudwebb** 2021-03-30 22:00 UTC
Labels: Bug, In Review, documentation

**Comment by dcorsus** [comment] 2021-04-01 16:16
Confirmed working in 4.1.15 
Thanks!
Dirk
