### ISSUE TITLE
Every new device is assigned to "Weather" category

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#234] opened 2021-12-04 11:34 UTC
HS 4.2.7.0

Is it me going crazy, or every device in HS is in "Weather" category?

![image](https://user-images.githubusercontent.com/2533315/144706363-11a9070e-16d6-49a1-9b2b-768dded1b863.png)

![image](https://user-images.githubusercontent.com/2533315/144707941-fbbc94ad-512f-40d3-848d-5cad208e3d54.png)

**Comment by alexbk66** [comment] 2021-12-04 11:48
Also it looks like AddRefToCategory() doesn't check if RefId is already in the category? So the RefId can be added multiple times.

And then to remove the RefId from category you need a "while" loop:

![image](https://user-images.githubusercontent.com/2533315/144708332-673163b2-067f-4ce6-a937-20a0a0f0f81c.png)

**Comment by alexbk66** [comment] 2021-12-04 23:17
And hs.GerRefsByCategory includes deleted devices

**Comment by spudwebb** [comment] 2021-12-07 19:28
I don't have every device in the "Weather" category on my system, not sure how you ended up in this state, if you can reproduce it please tell me how. You can check the Data/Categories.json to see the definition of the categories and their list of device refs.

I created HS-1495 and HS-1496 for bugs in AddRefToCategory and GerRefsByCategory .

**Comment by stefxx** [comment] 2021-12-13 14:49
I noticed that when you remove a device or feature, it won't be removed from the Categories.json. I had a situation before where a ref ID was reused, and caused it to have a category assigned already because of this. 

Might very well be what @alexbk66 is seeing.

**Comment by stefxx** [comment] 2021-12-13 14:53
I just had another look at Categories.json and noticed that some of the categories have the same device/feature more than once in the "ExplicitIncludeList".

**Comment by spudwebb** [comment] 2021-12-13 15:16
yes, this is what I saw too
HS-1495 is the issue for duplicates in ExplicitIncludeList
HS-1496 is the issue for ref id not removed from Categories.json when a device is deleted.

**Comment by spudwebb** [comment] 2022-02-07 21:41
Both HS-1495 and HS-1496 are fixed in HS 4.2.8.0

**Closed by spudwebb** 2022-02-07 21:41 UTC
Labels: Bug, To Do, HS Core, Jira
