### ISSUE TITLE
GetFeatureByAddress returns 'null' for feature - but GetDeviceByAddress returns HsDevice with type Feature

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#161] opened 2021-02-03 02:52 UTC
It only happens for one parent (shellyem3) and all children with "Power" in the Address

![image](https://user-images.githubusercontent.com/2533315/106690982-d4ce1c80-6626-11eb-81ec-e0abb4818c4f.png)

![image](https://user-images.githubusercontent.com/2533315/106691062-f7603580-6626-11eb-85d2-48a0780cee71.png)

**Comment by alexbk66** [comment] 2021-02-03 02:54
Interesting, it only happens for one parent (shellyem3) and all children with "Power" in the Address

**Comment by spudwebb** [comment] 2021-02-03 19:58
There is a bug in the PluginSdk that result in GetFeatureByAddress  or GetFeatureByRef returning null for some features. It only happens for some features with status/controls or status/graphics setup in a very specific way.

I believe it is what you ran into, I can confirm if you show me how the Status/Controls and Graphics are defined for this feature.

GetDeviceByAddress / GetDeviceByRef do not have this problem because they do not try to load the Status/Controls and Graphics, but you should not use those methods for features.

**Comment by alexbk66** [comment] 2021-02-04 04:32
![image](https://user-images.githubusercontent.com/2533315/106844820-b0913f00-66fd-11eb-8cfc-1bf0b961f40a.png)

In this case `allowNegative = true`

```
        public const int min_offs = 1000;
        public const int minval = Int32.MinValue + min_offs;
        public const int maxval = Int32.MaxValue - min_offs;
```

And:

![image](https://user-images.githubusercontent.com/2533315/106844983-0534ba00-66fe-11eb-9d2b-7ed307fc2d79.png)

![image](https://user-images.githubusercontent.com/2533315/106845046-2ac1c380-66fe-11eb-9bf4-0ee6f2784eb1.png)

**Comment by alexbk66** [comment] 2021-02-04 04:35
> you should not use those methods for features

At least I'm using it now as workaround until you fix the problem. And it does work ;) See very first code snippet in OP

**Comment by spudwebb** [comment] 2021-02-04 15:38
can you post a devices.json for this issue?

**Comment by alexbk66** [comment] 2021-02-05 15:40
> can you post a devices.json for this issue?

Looks like I can't reproduce now, may be other changes fixed this one.  But I'll remember about devices.json next time

**Comment by alexbk66** [comment] 2021-02-06 11:07
Happened again
[devices.zip](https://github.com/HomeSeer/Plugin-SDK/files/5936709/devices.zip)

**Comment by spudwebb** [comment] 2021-02-08 19:59
I couldn't reproduce the issue with your devices.json but I saw a problem in the definition of your StatusGraphics that may be related:
![image](https://user-images.githubusercontent.com/5427056/107274280-1f340c80-6a1e-11eb-9f7e-55978125da51.png)

you can't have a single value that is also part of another range

**Comment by alexbk66** [comment] 2021-02-09 01:48
Ok, I'll check

**Comment by tenholde** [comment] 2021-02-09 16:13
I have the same problem with retrieving Features for a few devices that are defined with a single Status/Contorls range of 1-204  and  a single Status/Graphics range of   0-204
![error](https://user-images.githubusercontent.com/19240584/107392513-60302d80-6abf-11eb-9bcd-81c1d0ae65a5.png)

**Comment by spudwebb** [comment] 2021-02-09 17:55
> I have the same problem with retrieving Features for a few devices that are defined with a single Status/Contorls range of 1-204 and a single Status/Graphics range of 0-204

This is a HS3 device, correct?
Can you post or send me your devices.json?

**Comment by tenholde** [comment] 2021-02-09 22:31
Running HS4 with a HS3 plugin device.   For example, devref 707.
![1](https://user-images.githubusercontent.com/19240584/107437217-42c98680-6af4-11eb-9d66-3b35d6949b20.png)

**Comment by tenholde** [comment] 2021-02-09 22:33
[devices.zip](https://github.com/HomeSeer/Plugin-SDK/files/5954657/devices.zip)

**Comment by tenholde** [comment] 2021-02-13 17:45
Just installed 4.1.12.0 and PluginSDK V1.2.2.0
Did not fix this problem
Feature 715 has a single Status/Control range of 1-204 and a single Status/Graphics range of 0-204 (there are several HS3 devices migrated to HS4 with this definition – mcsSprinklers)

GetAllDevices(True) returns nothing with an exception: A Status Graphic with that value set existsService: NO_VERSION

GetFeaturesByRef(715) returns Nothing with a message in the HS log: A status Graphic with that value exists.

**Comment by spudwebb** [comment] 2021-02-13 20:33
> Just installed 4.1.12.0 and PluginSDK V1.2.2.0
> Did not fix this problem
> Feature 715 has a single Status/Control range of 1-204 and a single Status/Graphics range of 0-204 (there are several HS3 devices migrated to HS4 with this definition – mcsSprinklers)
> 
> GetAllDevices(True) returns nothing with an exception: A Status Graphic with that value set existsService: NO_VERSION
> 
> GetFeaturesByRef(715) returns Nothing with a message in the HS log: A status Graphic with that value exists.

You're right this problem has not been fixed  in HS 4.1.12.0 / PluginSdk 1.2.2
We are working on it for the next release

**Comment by tenholde** [comment] 2021-02-13 20:39
Thank you

**Comment by spudwebb** [comment] 2021-02-15 18:51
tracked as HS-1122

**Comment by alexbk66** [comment] 2021-02-24 23:29
Any progress on this?  
I create my devices by address, a user reported that one device is created every time plugin is restarted
https://forums.homeseer.com/forum/hs4-products/hs4-plugins/wireless-receiver-transceiver-plug-ins-aa/ak-bond-alexbk66-aa/1458351-new-controls-created-on-hs4-restart#post1458654

**Comment by spudwebb** [comment] 2021-02-25 16:05
> Any progress on this?
> I create my devices by address, a user reported that one device is created every time plugin is restarted
> https://forums.homeseer.com/forum/hs4-products/hs4-plugins/wireless-receiver-transceiver-plug-ins-aa/ak-bond-alexbk66-aa/1458351-new-controls-created-on-hs4-restart#post1458654

This problem is not specific to GetFeatureByAddress , I believe it would happen also with GetFeatureByRef if you try to load the same feature. The problem is that there is bug when HS4 tries to load features with overlapping StatusGraphics. In the screenshot your user posted I can see that there is a graphic range for values 1-3 but also single value graphic for 2 and 3, that does not make sense so you should fix that. 
Also if values -1006, -1005, -1001, -1000 are status only, then they should not be created  as both StatusControl and StatusGraphic, you should create them as StatusGraphic only.

**Comment by alexbk66** [comment] 2021-02-26 06:15
> Also if values -1006, -1005, -1001, -1000 are status only, then they should not be created as both StatusControl and StatusGraphic, you should create them as StatusGraphic only.

I did fix this already - it's just not very clear what I should and shouldn't add...
But I can't see how it's related?  Is it because it tries to convert the device to "new" style"? 
It's interesting that the workaround in the OP does work (GetDeviceByAddress)

**Comment by spudwebb** [comment] 2021-03-30 22:18
Please test HS 4.1.15.0, this bug should be fixed.

**Closed by spudwebb** 2021-03-30 22:18 UTC
Labels: Bug, HS Core, In Progress
