### ISSUE TITLE
Feature control panels do not clear upon use of the control button

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#65] opened 2020-01-09 20:26 UTC
Version 4.0.1.5

Device has four features.  Each feature is controlled by a single button push.  From Device tile click on the selected feature icon.  Window pops up with the four features available for control.  Click again the desired feature and a second window pops up.  Click the button on the second popup to active the feature control.  The sequence is all as expected at this point.

The plugin executes in response to SetIoMulti call.  Again, as expected.

The browser remains unchanged as if the button was not pressed.  This results in a grayed-out background and two levels of popup tiles.

The user then needs to manually click on the upper-right X to remove the first tile.  Do it again on the second tile to remove the two tiles and remove the gray-out of the main page.

Expected response is that when the SetIoMulti call is executed the control tiles should be removed and the gray-out removed.  Without this feedback the user does not know if the button was recognized.  It is also a pain to close the two popup tiles manually.

**Comment by rjhdakota** [comment] 2020-01-21 20:58
The buttons do change color when you click on them. I can see cases where you might want to turn something ON then maybe change a dim level, all from this dialog. So I think closing it on control may not be desirable. Are you requesting that both dialogs close after control?

**Comment by mcsSolutions** [comment] 2020-01-21 22:46
What I observe is the following.  I can click on or off multiple times.  They do show a momentary click effect but if I am not paying close attention I do not know if I really did click it.  The feedback I expect when I did the control action is that both popup panels should be closed and the background gray-out removed.  I can see your point about a dimmer where you want the control to remain until the desired dim level is achieved using a trial and error method.  Perhaps a compromise is to keep the window up only on the set of controls that may be incremental such as dimmer or color picker.  These type of controls will provide the feedback that the user input was accepted because the feedback color will change or the slider position will change.  Another approach is that the Off/On buttons actually do change color based upon the command.  They can still be active buttons, but after clicking it then its color should change to indicate that the click action was accepted.

**Comment by jldubz** [comment] 2020-05-11 20:00
Referenced by PSDK-25

**Comment by jldubz** [comment] 2020-08-20 21:19
The UX for controls has been changed and this issue is no longer applicable to the new workflow.  Please let me know if there is still an issue with this for you and we can reopen this ticket. Thanks.

JL

**Closed by jldubz** 2020-08-20 21:19 UTC
Labels: Bug, HS Core, further investigation needed

**Comment by kvh83** [comment] 2020-08-24 07:57
I mentioned this during the beta, but the answer was that it is working as intended. It is designed to be a static display, not a dynamic one
https://forums.homeseer.com/forum/hs4-products/hs4-software/hs4-pro-beta-releases/1355221-%E2%9B%94-device-feature-popup-not-updated

**Comment by mcsSolutions** [comment] 2020-08-24 16:33
Issue #65 is not if the status updates or not, but that there is no feedback once a button is clicked.  Initial thought that the popup should close after the action was taken.  I was told that leaving the popup in place would allow multiple features to be controlled.  Leaving the popup is fine, but there needs to be some feedback that the user actions have been accepted or rejected.

**Comment by rjhdakota** [comment] 2020-08-24 17:19
What should be happening is that the status of the feature should update on that dialog, this will tell you that it executed. There is a development issue open on this and it should be fixed soon. Probably not until 4.1.6.0 though. I will link the ticket here so we can update this when it's addressed. HS-787

**Comment by spudwebb** [comment] 2021-06-17 17:49
FYI, the status is now dynamically updated in the features dialog in grid view in HS 4.1.17.0
